# Generated by Django 3.1 on 2020-08-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0003_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
